---
apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend-service
spec:
  selector:
    app: capstone-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-frontend
  template:
    metadata:
      labels:
        app: capstone-frontend
    spec:
      containers:
        - name: capstone-frontend
          image: 321304165861.dkr.ecr.us-west-2.amazonaws.com/capstone-frontend:v39
          ports:
            - containerPort: 80
